myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('worksites/', include('worksites.urls')),
    path('users/', include('users.urls')),
    path('profiles/', include('profiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name = "login"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.users_view, name="list"),
    path('<slug:slug>', views.user_page, name = "page")
]

myproject/users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext_lazy as _


# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        
        if not email:
            raise ValueError(_("An email is required."))
        if not password:
            raise ValueError(_('A password is required.'))
        email = self.normalize_email(email)
        user = self.model(email= email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)
        
        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        
        user = self.create_user(email, password=password, **extra_fields)
        user.is_admin = True
        return user

class CustomUser(AbstractUser):
    pass
    username = None
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    
    objects = CustomUserManager()
    
    def __str__(self):
        return self.email

myproject/users/forms.py
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class UserRegisterForm(UserCreationForm):
    
    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "email", "password", "is_staff", "is_active", "groups", "user_permissions"]
        
class UserUpdateForm(UserChangeForm):
     
    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "email", "password", "is_staff", "is_active", "groups", "user_permissions"]
 

        

myproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm
from users.models import CustomUser
# from django.contrib.auth.models import User


# Create your views here.

def register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            login(request, form.save())
            return redirect('users:list')
    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", { "form": form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("worksites:list")
                # return redirect("/")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", { "form": form })

def logout_view(request):
    if request.method == "POST":
        logout(request)
        # return redirect("users/login")
        return render(request, "users/logout.html")
    
    
def users_view(request):
    users = CustomUser.objects.all().order_by('-date')
    return render(request, 'users/users_list.html', { 'users': users })

def user_page(request, pk):
    user = CustomUser.objects.get(id=pk)
    return render(request, 'user/users_list.html', { 'user': user })

myproject/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}


{% block content %}
    <h1>User Login</h1>
    <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}

myproject/users/templates/users/logout.html
{% extends 'layout.html' %}

{% block title %}
    User Logout
{% endblock %}


{% block content %}
    <h1>You have been logged out</h1>
    <div>
        <small>
            <a href="{% url 'users:login' %}">Log In Again?</a>
        </small>
    </div>
    
{% endblock %}

myproject/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}


{% block content %}
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}

myproject/users/templates/users/user_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ worksite.title }}
{% endblock %}


{% block content %}
    <section>
        <img
            class="image"
            src="{{ user.profile.image.url }}"
            alt="{{ user.username}}"
        />
        <h1>{{ user.worksite.site_name }}</h1>
        <p>{{ .date }}</p>
        <p>{{ worksite.title }}</p>
        <p>{{ worksite.content }}</p>
        <p>Absentees: {{ worksite.absentees }}</p>
    
    </section>
{% endblock %}

myproject/users/templates/users/users_list.html
{% extends 'layout.html' %}

{% block title %}
    Users
{% endblock %}


{% block content %}
    <section>
    <h1>Users</h1>

    {% for user in users %}
        <article class="user">
            <h2>
                <a href="{% url 'users:page' slug=user.slug %}">
                {{ user.username }}
                </a>
            </h2>
            <p>{{ user.firstname }} {{ user.lastname }}</p>
            <p>At {{ user.worksite.site_name }}</p>
        </article>
    {% endfor %}
    </section>
{% endblock %}