myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('worksites/', include('worksites.urls')),
    path('users/', include('users.urls')),
    path('profiles/', include('profiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'



urlpatterns = [
    path('profile/<str:pk>/', views.profile, name="profile"),
    path('profile_edit/', views.profile_edit, name="profile_edit"),
]

myproject/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name = "login"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.users_view, name="list"),
    path('<slug:slug>', views.user_page, name = "page")
]

myproject/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
# from users.models import CustomUser
from myproject import settings
from PIL import Image


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE )
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    phone = models.CharField(default= '080-', max_length=11)
    site_name = models.CharField(default='EagleWings', max_length=225)
    
    def __str__(self):
        return f'{self.image} {self.user.first_name} Profile'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

myproject/profiles/forms.py
from django import forms
from .models import Profile
from users.models import CustomUser



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'phone']
        

myproject/profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from users.forms import UserUpdateForm
from users.models import CustomUser
from profiles.forms import ProfileUpdateForm
from django.contrib import messages

# Create your views here.

@login_required
def profile(request, pk):
    profile1 = CustomUser.objects.get(id = pk)
    return render(request, 'profiles/profile.html', { 'profile1': profile1 })

@login_required
def profile_edit(request):
    if request.method == "POST":
        # u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        # if u_form.is_valid() and p_form.is_valid():
        if p_form.is_valid():
            # u_form.save()
            p_form.save()
            messages.success(request, f"Your account has been updated!")
            return redirect('profiles:profile')
    else:
        # u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
    context = {
        # 'u_form': u_form,
        'p_form': p_form
    }
    
    return render(request, 'profiles/profile_edit.html', context)

myproject/profiles/templates/profiles/profile.html
{% extends 'layout.html' %}

{% block title %}
    {{ user.username }}
{% endblock %}


{% block content %}
    <section>
    {% if user.is_authenticated %}
        <img
            class="image"
            src="{{ user.profile.image.url }}"
            alt="{{ user.username}}"
        />
        <h2>Profile Info</h2>
        <h1>{{ user.username }}</h1>
        <p>{{ user.first_name }} {{ user.last_name }}</p>
        <p>{{ user.worksite.site_name }}</p>
        <p>{{ user.email }}</p>
        <p>{{ user.profile.phone }}</p>
    </section>
    {% endif %}
    <p>Check out my <a href="/profiles/profile_edit">Edit Profile</a> page.</p>

    
{% endblock %}

myproject/profiles/templates/profiles/profile_edit.html
{% extends 'layout.html' %}

{% block title %}
    Edit Profile
{% endblock %}


{% block content %}
    <h1>Edit Profile</h1>
        <form class="form-with-validation" action="{% url 'profiles:profile_edit' %}" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {% comment %} {{ u_form }} {% endcomment %}
            {{ p_form }}
            <button class="form-submit">Update</button>
        </form>
    
{% endblock %}