myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('worksites/', include('worksites.urls')),
    path('users/', include('users.urls')),
    path('profiles/', include('profiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name = "login"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.users_view, name="list"),
    path('<slug:slug>', views.user_page, name = "page")
]

myproject/worksites/urls.py
from django.urls import path, include
from . import views

app_name = 'worksites'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('single-list/', views.posts_user_list, name="single-list"),
    path('new-post/', views.post_new, name= "new-post"),
    path('update-post/', views.post_update, name = "update-post"),
    path('<slug:slug>', views.post_page, name = "page"),
]

myproject/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}


{% block content %}
    {% for user in users %}
        <article>
            <img src="{{ user.profile.image.url }}">
            <div>
                <p>{{ user.username }}</p>
                <p>{{ user.email }}</p>
                <p>{{ user.profile.phone }}</p>
            </div>
        </article>
    {% endfor %}
    <h1>Home</h1>
    {% if user.is_authenticated %}
        <p>Check out my <a href="/profiles/profile">User Profile</a> page.</p>
    {% endif %}
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Employee App
        {% endblock %}
    </title>
    {% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
    {% comment %} <script src="{% static 'js/main.js' %}" defer></script> {% endcomment %}
</head>
<body>
    <nav>
        <a href="/">
            <span role="img" aria-label= "Home" title="Home">🏠</span>
        </a> |

        {% if user.is_staff%}
            <a href="{% url 'users:register' %}">
                <span role="img" aria-label="User Registration" title="Registration">🚀</span>
            </a> |
            <a href="{% url 'worksites:list' %}">
                <span role="img" aria-label="Worksites" title="Worksites">📰</span>
            </a> |
            <a href="{% url 'worksites:new-post' %}">
                <span role="img" aria-label="New Post" title="New Post">🆕</span>
            </a> |
        {% endif %}
        
        {% if not user.is_staff and user.is_authenticated %}
            <a href="{% url 'worksites:new-post' %}">
                <span role="img" aria-label="New Post" title="New Post">🆕</span>
            </a> |
            <a href="{% url 'worksites:single-list' %}">
                <span role="img" aria-label="my posts" title="My Posts">📰</span>
            </a> |

        {% endif %}
    
        {% if user.is_authenticated %}
            {% comment %} <a href="{% url 'profiles:profile/<str:pk>' %}">
                <span role="img" aria-label="User profile" title="profile">Profile👨‍🏭</span>
            </a>  {% endcomment %}
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button" aria-label="User Logout" title="User Logout">👋</button>
            </form>
        {% else %}
            <a href="{% url 'users:login' %}">
                <span role="img" aria-label="User Login" title="Login">🔑</span>
            </a> 
        {% endif %}
    </nav>
    <main>
        <div>
            <div>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>