myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('worksites/', include('worksites.urls')),
    path('users/', include('users.urls')),
    path('profiles/', include('profiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name = "login"),
    path('logout/', views.logout_view, name="logout"),
    path('', views.users_view, name="list"),
    path('<slug:slug>', views.user_page, name = "page")
]

myproject/worksites/urls.py
from django.urls import path, include
from . import views

app_name = 'worksites'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('single-list/', views.posts_user_list, name="single-list"),
    path('new-post/', views.post_new, name= "new-post"),
    path('update-post/', views.post_update, name = "update-post"),
    path('<slug:slug>', views.post_page, name = "page"),
]

myproject/worksites/models.py
from django.db import models
from users.models import CustomUser
from django.urls import reverse

# Create your models here.
class Worksite(models.Model):
    site_name = models.CharField(max_length=100)
    title = models.CharField(max_length=75)
    content = models.TextField()
    slug = models.SlugField()
    absentees = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("worksite-detail", kwargs={"pk": self.pk})
    

myproject/worksites/forms.py
from django import forms
from . import models


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Worksite
        fields = ['site_name','title','content','slug','absentees']
        
        
class UpdatePost(forms.ModelForm):
    class Meta:
        model = models.Worksite
        fields = ['title','content','absentees']


class DeletePost():
    pass

myproject/worksites/views.py
from django.shortcuts import render, redirect
from .models import Worksite
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . import forms


# Create your views here.
#request -> response

def posts_list(request):
    worksites = Worksite.objects.all().order_by('-date')
    return render(request, 'worksites/posts_list.html', { 'worksites': worksites })


@login_required(login_url='/users/login')
def posts_user_list(request):
    user = request.user
    user_posts = Worksite.objects.filter(author =request.user).order_by('-date')
    return render(request, 'worksites/post_user_list.html', { "user_posts": user_posts, "user": user})


def post_page(request, slug):
    worksite = Worksite.objects.get(slug=slug)
    return render(request, 'worksites/post_page.html', { 'worksite': worksite })

@login_required(login_url='/users/login')
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            messages.success(request, f'Your post is successful!')
            return redirect('worksites:single-list')
    else:
        form = forms.CreatePost()
    return render(request, 'worksites/post_new.html', { 'form': form })

@login_required(login_url='/users/login')
def post_update(request):
    if request.method == 'PATCH':
        form = forms.UpdatePost(request.PATCH, request.FILES, instance=request.user)
        if form.is_valid():
            updatepost = form.save(commit=False)
            updatepost.author = request.user
            updatepost.save()
            messages.success(request, f'Your post has been updated!')
            return redirect('worksites:single-list')
    else:
        form = forms.UpdatePost(instance=request.user)
    return render(request, 'worksites/post_edit.html', { 'form': form })

myproject/worksites/templates/worksites/post_edit.html
{% extends 'layout.html' %}

{% block title %}
    Edit Post
{% endblock %}


{% block content %}
    <section>
        <h1>Edit Post</h1>
        <form class="form-with-validation" action="{% url 'worksites:update-post' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Update Post</button>
        </form>
        <a href="/worksites/update-post/"><button>Edit</button></a>
    </section>
    
{% endblock %}

myproject/worksites/templates/worksites/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}


{% block content %}
    <section>
        <h1>New Post</h1>
        <form class="form-with-validation" action="{% url 'worksites:new-post' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Add Post</button>
        </form>
    </section>
    
{% endblock %}

myproject/worksites/templates/worksites/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ worksite.title }}
{% endblock %}


{% block content %}
    <section>
        <img
            class="image"
            src="{{ worksite.author.profile.image.url }}"
            alt="{{ worksite.author.username}}"
        />
        <h1>{{ worksite.site_name }}</h1>
        <p>{{ worksite.date }}</p>
        <p>{{ worksite.title }}</p>
        <p>{{ worksite.content }}</p>
        <p>Absentees: {{ worksite.absentees }}</p>
    
    </section>
{% endblock %}

myproject/worksites/templates/worksites/post_user_list.html
{% extends 'layout.html' %}

{% block title %}
    Worksites
{% endblock %}


{% block content %}
    <section>
    {% if user.is_authenticated %}
        <h1>{{ user.first_name|upper }}</h1>
    {% endif %}
        <p>My Posts</P>

    {% for worksite in user_posts %}
        <article class="worksite">
            <h2>
                <a href="{% url 'worksites:page' slug=worksite.slug %}">
                {{ worksite.title }}
                </a>
            </h2>
            <p>{{ worksite.date|date:"F d, Y" }} by {{ worksite.author.first_name }}</p>
            <p>{{ worksite.site_name|upper }}</p>
            <a href="/worksites/update-post/"><button>Edit</button></a>
            <hr>
        </article>
    {% endfor %}
    </section>
{% endblock %}

myproject/worksites/templates/worksites/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Worksites
{% endblock %}


{% block content %}
{% if user.is_staff %}
    <section>
    <h1>Posts</h1>
    <p><a href="/worksites/single-list/">Check my Posts</a></p>

    {% for worksite in worksites %}
        <article class="worksite">
            <h2>
                <a href="{% url 'worksites:page' slug=worksite.slug %}">
                {{ worksite.title }}
                </a>
            </h2>
            <p>{{ worksite.date|date:"F d, Y" }} by {{ worksite.author.first_name|title }}</p>
            <p>{{ worksite.site_name|upper }}</p>
            <a href="/worksites/update-post/"><button>Edit</button></a>
            <hr>
        </article>
    {% endfor %}
    </section>
{% endif %}
{% endblock %}